spring.application.name=events

spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing
spring.datasource.username=postgres
spring.datasource.password=8701

# Automatically generate or update database tables based on your code entities
spring.jpa.hibernate.ddl-auto=update

# Print SQL queries to the console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-ms=86400000